
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/07a_lsuv_my_reimplementation.ipynb

from exports.nb_07 import *

def get_batch(dl, run):
    run.xb, run.yb = next(iter(dl))
    for cb in run.cbs: cb.set_runner(run)
    run('begin_batch')
    return run.xb, run.yb

def find_modules(module, condition):
    if condition(module): return [module]
    return sum([find_modules(o, condition) for o in module.children()], [])

def lsuv_module(module, xb):
    h = ForwardHook(module, append_stats)

    while model(xb) is not None and abs(h.var - 1) > 1e-3: module.weight.data /= h.std
    while model(xb) is not None and abs(h.mean)    > 1e-3: module.activation_bias -= h.mean

    h.remove()
    return h.mean, h.var